# yaml-language-server: $schema=https://render.com/schema/render.yaml.json

version: "1"

projects:
  - name: projecttemplate
    environments:
      - name: Production

        services:
          # =========================
          # API SERVER
          # =========================
          - name: projecttemplate-server
            type: web
            runtime: node
            plan: free
            autoDeployTrigger: "commit"

            buildFilter:
              paths:
                - apps/server/**
                - packages/**

            # Build just server:
            # buildCommand: corepack enable && yarn install --immutable && yarn workspaces foreach --from @rejc2/projecttemplate-server --recursive --topological run build
            # Build everything:
            buildCommand: corepack enable && yarn install --immutable && yarn build
            startCommand: yarn workspace @rejc2/projecttemplate-server prisma:migrate && yarn workspace @rejc2/projecttemplate-server prisma:seed && yarn workspace @rejc2/projecttemplate-server start

            healthCheckPath: /health

            # domains:
            #   - api.projecttemplate.app

            envVars:
              - key: CORS_ORIGIN_URL
                sync: false
              - key: DATABASE_URL
                fromDatabase:
                  name: projecttemplate-db
                  property: connectionString
              - key: GOOGLE_CLIENT_ID
                sync: false
              - key: GOOGLE_CLIENT_SECRET
                sync: false
              - key: NODE_ENV
                value: production
              # - key: REDIS_URL
              #   fromService:
              #     name: projecttemplate-redis
              #     property: connectionString
              #     type: redis
              - key: SESSION_SECRET
                generateValue: true

            previews:
              generation: manual

          # =========================
          # FRONTEND STATIC SITE
          # =========================
          - name: projecttemplate-web
            type: web
            runtime: static
            autoDeployTrigger: "commit"

            buildFilter:
              paths:
                - apps/web/**
                - packages/**

            buildCommand: corepack enable && yarn install --immutable && yarn workspaces foreach --from @rejc2/projecttemplate-web --recursive --topological run build
            staticPublishPath: apps/web/dist

            routes:
              # Rewrites all paths to index.html for client-side routing
              - type: rewrite
                source: /*
                destination: /index.html

            # domains:
            #   - projecttemplate.app
            #   - www.projecttemplate.app

            envVars:
              - key: SKIP_INSTALL_DEPS
                value: "true"
              - key: VITE_API_URL
                sync: false

            previews:
              generation: manual

          # =========================
          # REDIS
          # =========================
          # (Disabled due to limit of 1 free Redis instance)
          # - type: redis
          #   name: projecttemplate-redis
          #   plan: free
          #   ipAllowList: [] # allow internal connections only

        databases:
          # =========================
          # POSTGRES DB
          # =========================
          - name: projecttemplate-db
            databaseName: projecttemplate
            plan: free
            previewPlan: starter
