# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: project-template
      POSTGRES_PASSWORD: project-template
      POSTGRES_DB: project-template
    volumes:
      - project-template_pgdata:/var/lib/postgresql/data

  postgres_shadow:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: project-template
      POSTGRES_PASSWORD: project-template
      POSTGRES_DB: project-template_shadow

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  project-template_pgdata:
