# syntax=docker/dockerfile:1.7-labs
FROM node:26-trixie AS base
RUN npm install -g corepack && corepack enable

WORKDIR /repo

# Copy package files for all workspaces:
COPY package.json yarn.lock .yarnrc.yml ./
COPY --parents apps/*/package.json ./
COPY --parents dev-packages/*/package.json ./
COPY --parents packages/*/package.json ./
COPY --parents test-packages/*/package.json ./

RUN --mount=type=cache,target=/root/.yarn/berry/cache \
	yarn install --immutable

COPY lingui.config.ts ./
