# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Prisma CI Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prisma-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      postgres_shadow:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db_shadow
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Set database URLs
        run: |
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/test_db" >> $GITHUB_ENV
          echo "SHADOW_DATABASE_URL=postgresql://postgres:postgres@localhost:5433/test_db_shadow" >> $GITHUB_ENV

      - name: Generate Prisma Client
        run: yarn workspace @rejc2/projecttemplate-server prisma:generate

      - name: Run Migrations
        run: yarn workspace @rejc2/projecttemplate-server prisma:migrate

      - name: Check for schema drift
        working-directory: apps/server
        run: |
          yarn prisma migrate diff \
            --from-migrations ./prisma/schema/migrations \
            --to-schema ./prisma/schema \
            --exit-code
